In [113]:
#Evaluacion_1

In [114]:
import pandas as pd
deudapbiLink='https://github.com/ZairaYacsavilca/evaluaci-n_1/raw/main/data/variable_deuda_PBI.csv'
gastosaludLink='https://github.com/ZairaYacsavilca/evaluaci-n_1/raw/main/data/variable_gasto_salud.csv'
hdiLink='https://github.com/ZairaYacsavilca/evaluaci-n_1/raw/main/data/Variable_Naciones_Unidas.csv'

deudapbi=pd.read_csv(deudapbiLink)
gastosalud=pd.read_csv(gastosaludLink)
hdi=pd.read_csv(hdiLink)

In [115]:
#amount of rows of each DF:
deudapbi.shape,gastosalud.shape,hdi.shape

((190, 2), (192, 2), (193, 2))

In [116]:
#column names of each DF:
deudapbi.columns,gastosalud.columns,hdi.columns

(Index(['Countries', 'Debt ($M)'], dtype='object'),
 Index(['Countries', 'Gov. Health Exp.($M)'], dtype='object'),
 Index(['Countries', 'HDI'], dtype='object'))

In [117]:
#merge of DF:
merge1=deudapbi.merge(gastosalud,how='inner',left_on='Countries',right_on='Countries').merge(hdi,how='inner',left_on='Countries',right_on='Countries')
merge1

           Countries   Debt ($M)  Gov. Health Exp.($M)    HDI
0     United States   29,476,402  3,590,550,278,000.00  0.921
1    United Kingdom    3,151,536     87,073,157,032.30  0.929
2           Germany    2,711,576    445,746,483,000.00  0.942
3            France    3,106,402    279,900,617,256.00  0.903
4             Japan   12,783,842    213,703,956,338.90  0.925
..               ...         ...                   ...    ...
182           Samoa          364                  36.2  0.707
183           Yemen       18,092                   183  0.455
184    South Africa      288,114             15,210.00  0.713
185          Zambia       24,538                 446.9  0.565
186        Zimbabwe    1,905,213                 732.5  0.593

[187 rows x 4 columns]

In [118]:
#amount of rows in the merge:
merge1.shape

(187, 4)

In [119]:
#Rename the Countries column
merge1=merge1.rename(columns={"Countries": "Country"})
merge1

             Country   Debt ($M)  Gov. Health Exp.($M)    HDI
0     United States   29,476,402  3,590,550,278,000.00  0.921
1    United Kingdom    3,151,536     87,073,157,032.30  0.929
2           Germany    2,711,576    445,746,483,000.00  0.942
3            France    3,106,402    279,900,617,256.00  0.903
4             Japan   12,783,842    213,703,956,338.90  0.925
..               ...         ...                   ...    ...
182           Samoa          364                  36.2  0.707
183           Yemen       18,092                   183  0.455
184    South Africa      288,114             15,210.00  0.713
185          Zambia       24,538                 446.9  0.565
186        Zimbabwe    1,905,213                 732.5  0.593

[187 rows x 4 columns]

In [120]:
#the Country column capitalized
merge1['Country']=merge1['Country'].str.upper()
merge1

             Country   Debt ($M)  Gov. Health Exp.($M)    HDI
0     UNITED STATES   29,476,402  3,590,550,278,000.00  0.921
1    UNITED KINGDOM    3,151,536     87,073,157,032.30  0.929
2           GERMANY    2,711,576    445,746,483,000.00  0.942
3            FRANCE    3,106,402    279,900,617,256.00  0.903
4             JAPAN   12,783,842    213,703,956,338.90  0.925
..               ...         ...                   ...    ...
182           SAMOA          364                  36.2  0.707
183           YEMEN       18,092                   183  0.455
184    SOUTH AFRICA      288,114             15,210.00  0.713
185          ZAMBIA       24,538                 446.9  0.565
186        ZIMBABWE    1,905,213                 732.5  0.593

[187 rows x 4 columns]

In [121]:
import pandas as pd
isosLink='https://github.com/ZairaYacsavilca/evaluaci-n_1/raw/main/data/country_isos.csv'

isos=pd.read_csv(isosLink)
isos

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
167,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,YEMEN,The Republic of Yemen,.ye,YE,YEM
169,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
170,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [122]:
# Countries in 'merge1' but NOT in 'isos'
OnlyMerge1=set(merge1.Country)-set(isos.Country)
OnlyMerge1

{'AFGHANISTAN ',
 'ALBANIA ',
 'ALGERIA ',
 'ANDORRA ',
 'ANGOLA ',
 'ANTIGUA AND BARBUDA ',
 'ARGENTINA ',
 'ARMENIA ',
 'AUSTRALIA ',
 'AUSTRIA ',
 'AZERBAIJAN ',
 'BAHAMAS ',
 'BAHRAIN ',
 'BANGLADESH ',
 'BARBADOS ',
 'BELARUS ',
 'BELGIUM ',
 'BELIZE ',
 'BENIN ',
 'BHUTAN ',
 'BOLIVIA ',
 'BOSNIA AND HERZEGOVINA ',
 'BOTSWANA ',
 'BRAZIL ',
 'BRUNEI ',
 'BULGARIA ',
 'BURKINA FASO ',
 'BURUNDI ',
 'CABO VERDE ',
 'CAMBODIA ',
 'CAMEROON ',
 'CANADA ',
 'CENTRAL AFRICAN REPUBLIC ',
 'CHAD ',
 'CHILE ',
 'CHINA ',
 'COLOMBIA ',
 'COMOROS ',
 'COSTA RICA ',
 'CROATIA ',
 'CYPRUS ',
 'CZECHIA ',
 "CÃ”TE D'IVOIRE ",
 'DEMOCRATIC REPUBLIC OF THE CONGO ',
 'DENMARK ',
 'DJIBOUTI ',
 'DOMINICA ',
 'DOMINICAN REPUBLIC ',
 'ECUADOR ',
 'EGYPT ',
 'EL SALVADOR ',
 'EQUATORIAL GUINEA ',
 'ERITREA ',
 'ESTONIA ',
 'ESWATINI ',
 'ETHIOPIA ',
 'FEDERATED STATES OF MICRONESIA ',
 'FIJI ',
 'FINLAND ',
 'FRANCE ',
 'GABON ',
 'GEORGIA ',
 'GERMANY ',
 'GHANA ',
 'GREECE ',
 'GRENADA ',
 'GUATEMALA ',
 'GUINEA ',
 'GUINEA-BISSAU ',
 'GUYANA ',
 'HAITI ',
 'HONDURAS ',
 'HUNGARY ',
 'ICELAND ',
 'INDIA ',
 'INDONESIA ',
 'IRAN ',
 'IRAQ ',
 'IRELAND ',
 'ISRAEL ',
 'ITALY ',
 'JAMAICA ',
 'JAPAN ',
 'JORDAN ',
 'KAZAKHSTAN ',
 'KENYA ',
 'KIRIBATI ',
 'KUWAIT ',
 'KYRGYZSTAN ',
 'LAOS ',
 'LATVIA ',
 'LEBANON ',
 'LESOTHO ',
 'LIBERIA ',
 'LIBYA ',
 'LITHUANIA ',
 'LUXEMBOURG ',
 'MADAGASCAR ',
 'MALAWI ',
 'MALAYSIA ',
 'MALDIVES ',
 'MALI ',
 'MALTA ',
 'MARSHALL ISLANDS ',
 'MAURITANIA ',
 'MAURITIUS ',
 'MEXICO ',
 'MOLDOVA ',
 'MONGOLIA ',
 'MONTENEGRO ',
 'MOROCCO ',
 'MOZAMBIQUE ',
 'MYANMAR ',
 'NAMIBIA ',
 'NAURU ',
 'NEPAL ',
 'NETHERLANDS ',
 'NEW ZEALAND ',
 'NICARAGUA ',
 'NIGER ',
 'NIGERIA ',
 'NORTH MACEDONIA ',
 'NORWAY ',
 'OMAN ',
 'PAKISTAN ',
 'PANAMA ',
 'PAPUA NEW GUINEA ',
 'PARAGUAY ',
 'PERU ',
 'PHILIPPINES ',
 'POLAND ',
 'PORTUGAL ',
 'QATAR ',
 'REPUBLIC OF THE CONGO ',
 'ROMANIA ',
 'RUSSIA ',
 'RWANDA ',
 'SAINT KITTS AND NEVIS ',
 'SAINT LUCIA ',
 'SAINT VINCENT AND THE GRENADINES ',
 'SAMOA ',
 'SAN MARINO ',
 'SAO TOME AND PRINCIPE ',
 'SAUDI ARABIA ',
 'SENEGAL ',
 'SERBIA ',
 'SEYCHELLES ',
 'SIERRA LEONE ',
 'SINGAPORE ',
 'SLOVAKIA ',
 'SLOVENIA ',
 'SOLOMON ISLANDS ',
 'SOUTH AFRICA ',
 'SOUTH KOREA ',
 'SOUTH SUDAN ',
 'SPAIN ',
 'SRI LANKA ',
 'SUDAN ',
 'SURINAME ',
 'SWEDEN ',
 'SWITZERLAND ',
 'SYRIA ',
 'TAJIKISTAN ',
 'TANZANIA ',
 'THAILAND ',
 'THE GAMBIA ',
 'TIMOR-LESTE ',
 'TOGO ',
 'TONGA ',
 'TRINIDAD AND TOBAGO ',
 'TUNISIA ',
 'TURKMENISTAN ',
 'TUVALU ',
 'TÃœRKIYE ',
 'UGANDA ',
 'UKRAINE ',
 'UNITED ARAB EMIRATES ',
 'UNITED KINGDOM ',
 'UNITED STATES ',
 'URUGUAY ',
 'UZBEKISTAN ',
 'VANUATU ',
 'VENEZUELA ',
 'VIET NAM ',
 'YEMEN ',
 'ZAMBIA ',
 'ZIMBABWE '}

In [123]:
# Countries in 'isos' but NOT in 'merge1'
OnlyIsos=set(isos.Country)-set(merge1.Country)
OnlyIsos

{'AFGHANISTAN',
 'ALBANIA',
 'ALGERIA',
 'ANGOLA',
 'ANTIGUA AND BARBUDA',
 'ARGENTINA',
 'ARMENIA',
 'AUSTRALIA',
 'AUSTRIA',
 'AZERBAIJAN',
 'BAHAMAS (THE)',
 'BAHRAIN',
 'BANGLADESH',
 'BARBADOS',
 'BELARUS',
 'BELGIUM',
 'BELIZE',
 'BENIN',
 'BHUTAN',
 'BOLIVIA (PLURINATIONAL STATE OF)',
 'BOSNIA AND HERZEGOVINA',
 'BOTSWANA',
 'BRAZIL',
 'BRUNEI DARUSSALAM',
 'BULGARIA',
 'BURKINA FASO',
 'BURUNDI',
 'CABO VERDE',
 'CAMBODIA',
 'CAMEROON',
 'CANADA',
 'CENTRAL AFRICAN REPUBLIC (THE)',
 'CHAD',
 'CHILE',
 'CHINA',
 'COLOMBIA',
 'COMOROS (THE)',
 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
 'CONGO (THE)',
 'COSTA RICA',
 'CROATIA',
 'CUBA',
 'CYPRUS',
 'CZECHIA',
 "CâˆšÃ®TE D'IVOIRE",
 'DENMARK',
 'DJIBOUTI',
 'DOMINICAN REPUBLIC (THE)',
 'ECUADOR',
 'EGYPT',
 'EL SALVADOR',
 'EQUATORIAL GUINEA',
 'ESTONIA',
 'ESWATINI',
 'ETHIOPIA',
 'FIJI',
 'FINLAND',
 'FRANCE',
 'GABON',
 'GAMBIA (THE)',
 'GEORGIA',
 'GERMANY',
 'GHANA',
 'GREECE',
 'GRENADA',
 'GUATEMALA',
 'GUINEA',
 'GUINEA-BISSAU',
 'GUYANA',
 'HAITI',
 'HONDURAS',
 'HUNGARY',
 'ICELAND',
 'INDIA',
 'INDONESIA',
 'IRAN (ISLAMIC REPUBLIC OF)',
 'IRAQ',
 'IRELAND',
 'ITALY',
 'JAMAICA',
 'JAPAN',
 'JORDAN',
 'KAZAKHSTAN',
 'KENYA',
 'KOREA (THE REPUBLIC OF)',
 'KUWAIT',
 'KYRGYZSTAN',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
 'LATVIA',
 'LEBANON',
 'LESOTHO',
 'LIBERIA',
 'LIBYA',
 'LITHUANIA',
 'LUXEMBOURG',
 'MADAGASCAR',
 'MALAWI',
 'MALAYSIA',
 'MALDIVES',
 'MALI',
 'MALTA',
 'MAURITANIA',
 'MAURITIUS',
 'MEXICO',
 'MICRONESIA (FEDERATED STATES OF)',
 'MOLDOVA (THE REPUBLIC OF)',
 'MONGOLIA',
 'MONTENEGRO',
 'MOROCCO',
 'MOZAMBIQUE',
 'MYANMAR',
 'NAMIBIA',
 'NEPAL',
 'NETHERLANDS (THE)',
 'NEW ZEALAND',
 'NICARAGUA',
 'NIGER (THE)',
 'NIGERIA',
 'NORTH MACEDONIA',
 'NORWAY',
 'OMAN',
 'PAKISTAN',
 'PANAMA',
 'PAPUA NEW GUINEA',
 'PARAGUAY',
 'PERU',
 'PHILIPPINES (THE)',
 'POLAND',
 'PORTUGAL',
 'QATAR',
 'ROMANIA',
 'RUSSIAN FEDERATION (THE)',
 'RWANDA',
 'SAMOA',
 'SAO TOME AND PRINCIPE',
 'SAUDI ARABIA',
 'SENEGAL',
 'SERBIA',
 'SEYCHELLES',
 'SIERRA LEONE',
 'SINGAPORE',
 'SLOVAKIA',
 'SLOVENIA',
 'SOLOMON ISLANDS',
 'SOUTH SUDAN',
 'SPAIN',
 'SRI LANKA',
 'SUDAN (THE)',
 'SURINAME',
 'SWEDEN',
 'SWITZERLAND',
 'TAJIKISTAN',
 'TANZANIA, THE UNITED REPUBLIC OF',
 'THAILAND',
 'TIMOR-LESTE',
 'TOGO',
 'TRINIDAD AND TOBAGO',
 'TUNISIA',
 'TURKEY',
 'TURKMENISTAN',
 'UGANDA',
 'UKRAINE',
 'UNITED ARAB EMIRATES (THE)',
 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
 'URUGUAY',
 'UZBEKISTAN',
 'VIET NAM',
 'YEMEN',
 'ZAMBIA',
 'ZIMBABWE'}

In [124]:
from thefuzz import process as fz

[(f,fz.extractOne(f, OnlyMerge1)) for f in sorted(OnlyIsos)]

[('AFGHANISTAN', ('AFGHANISTAN ', 100)),
 ('ALBANIA', ('ALBANIA ', 100)),
 ('ALGERIA', ('ALGERIA ', 100)),
 ('ANGOLA', ('ANGOLA ', 100)),
 ('ANTIGUA AND BARBUDA', ('ANTIGUA AND BARBUDA ', 100)),
 ('ARGENTINA', ('ARGENTINA ', 100)),
 ('ARMENIA', ('ARMENIA ', 100)),
 ('AUSTRALIA', ('AUSTRALIA ', 100)),
 ('AUSTRIA', ('AUSTRIA ', 100)),
 ('AZERBAIJAN', ('AZERBAIJAN ', 100)),
 ('BAHAMAS (THE)', ('BAHAMAS ', 90)),
 ('BAHRAIN', ('BAHRAIN ', 100)),
 ('BANGLADESH', ('BANGLADESH ', 100)),
 ('BARBADOS', ('BARBADOS ', 100)),
 ('BELARUS', ('BELARUS ', 100)),
 ('BELGIUM', ('BELGIUM ', 100)),
 ('BELIZE', ('BELIZE ', 100)),
 ('BENIN', ('BENIN ', 100)),
 ('BHUTAN', ('BHUTAN ', 100)),
 ('BOLIVIA (PLURINATIONAL STATE OF)', ('BOLIVIA ', 90)),
 ('BOSNIA AND HERZEGOVINA', ('BOSNIA AND HERZEGOVINA ', 100)),
 ('BOTSWANA', ('BOTSWANA ', 100)),
 ('BRAZIL', ('BRAZIL ', 100)),
 ('BRUNEI DARUSSALAM', ('BRUNEI ', 90)),
 ('BULGARIA', ('BULGARIA ', 100)),
 ('BURKINA FASO', ('BURKINA FASO ', 100)),
 ('BURUNDI', ('BURUNDI ', 100)),
 ('CABO VERDE', ('CABO VERDE ', 100)),
 ('CAMBODIA', ('CAMBODIA ', 100)),
 ('CAMEROON', ('CAMEROON ', 100)),
 ('CANADA', ('CANADA ', 100)),
 ('CENTRAL AFRICAN REPUBLIC (THE)', ('CENTRAL AFRICAN REPUBLIC ', 95)),
 ('CHAD', ('CHAD ', 100)),
 ('CHILE', ('CHILE ', 100)),
 ('CHINA', ('CHINA ', 100)),
 ('COLOMBIA', ('COLOMBIA ', 100)),
 ('COMOROS (THE)', ('COMOROS ', 90)),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
  ('DEMOCRATIC REPUBLIC OF THE CONGO ', 95)),
 ('CONGO (THE)', ('SAINT VINCENT AND THE GRENADINES ', 86)),
 ('COSTA RICA', ('COSTA RICA ', 100)),
 ('CROATIA', ('CROATIA ', 100)),
 ('CUBA', ('ECUADOR ', 68)),
 ('CYPRUS', ('CYPRUS ', 100)),
 ('CZECHIA', ('CZECHIA ', 100)),
 ("CâˆšÃ®TE D'IVOIRE", ("CÃ”TE D'IVOIRE ", 96)),
 ('DENMARK', ('DENMARK ', 100)),
 ('DJIBOUTI', ('DJIBOUTI ', 100)),
 ('DOMINICAN REPUBLIC (THE)', ('DOMINICAN REPUBLIC ', 95)),
 ('ECUADOR', ('ECUADOR ', 100)),
 ('EGYPT', ('EGYPT ', 100)),
 ('EL SALVADOR', ('EL SALVADOR ', 100)),
 ('EQUATORIAL GUINEA', ('EQUATORIAL GUINEA ', 100)),
 ('ESTONIA', ('ESTONIA ', 100)),
 ('ESWATINI', ('ESWATINI ', 100)),
 ('ETHIOPIA', ('ETHIOPIA ', 100)),
 ('FIJI', ('FIJI ', 100)),
 ('FINLAND', ('FINLAND ', 100)),
 ('FRANCE', ('FRANCE ', 100)),
 ('GABON', ('GABON ', 100)),
 ('GAMBIA (THE)', ('THE GAMBIA ', 95)),
 ('GEORGIA', ('GEORGIA ', 100)),
 ('GERMANY', ('GERMANY ', 100)),
 ('GHANA', ('GHANA ', 100)),
 ('GREECE', ('GREECE ', 100)),
 ('GRENADA', ('GRENADA ', 100)),
 ('GUATEMALA', ('GUATEMALA ', 100)),
 ('GUINEA', ('GUINEA ', 100)),
 ('GUINEA-BISSAU', ('GUINEA-BISSAU ', 100)),
 ('GUYANA', ('GUYANA ', 100)),
 ('HAITI', ('HAITI ', 100)),
 ('HONDURAS', ('HONDURAS ', 100)),
 ('HUNGARY', ('HUNGARY ', 100)),
 ('ICELAND', ('ICELAND ', 100)),
 ('INDIA', ('INDIA ', 100)),
 ('INDONESIA', ('INDONESIA ', 100)),
 ('IRAN (ISLAMIC REPUBLIC OF)', ('IRAN ', 90)),
 ('IRAQ', ('IRAQ ', 100)),
 ('IRELAND', ('IRELAND ', 100)),
 ('ITALY', ('ITALY ', 100)),
 ('JAMAICA', ('JAMAICA ', 100)),
 ('JAPAN', ('JAPAN ', 100)),
 ('JORDAN', ('JORDAN ', 100)),
 ('KAZAKHSTAN', ('KAZAKHSTAN ', 100)),
 ('KENYA', ('KENYA ', 100)),
 ('KOREA (THE REPUBLIC OF)', ('SOUTH KOREA ', 86)),
 ('KUWAIT', ('KUWAIT ', 100)),
 ('KYRGYZSTAN', ('KYRGYZSTAN ', 100)),
 ("LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)", ('THE GAMBIA ', 86)),
 ('LATVIA', ('LATVIA ', 100)),
 ('LEBANON', ('LEBANON ', 100)),
 ('LESOTHO', ('LESOTHO ', 100)),
 ('LIBERIA', ('LIBERIA ', 100)),
 ('LIBYA', ('LIBYA ', 100)),
 ('LITHUANIA', ('LITHUANIA ', 100)),
 ('LUXEMBOURG', ('LUXEMBOURG ', 100)),
 ('MADAGASCAR', ('MADAGASCAR ', 100)),
 ('MALAWI', ('MALAWI ', 100)),
 ('MALAYSIA', ('MALAYSIA ', 100)),
 ('MALDIVES', ('MALDIVES ', 100)),
 ('MALI', ('MALI ', 100)),
 ('MALTA', ('MALTA ', 100)),
 ('MAURITANIA', ('MAURITANIA ', 100)),
 ('MAURITIUS', ('MAURITIUS ', 100)),
 ('MEXICO', ('MEXICO ', 100)),
 ('MICRONESIA (FEDERATED STATES OF)', ('FEDERATED STATES OF MICRONESIA ', 95)),
 ('MOLDOVA (THE REPUBLIC OF)', ('MOLDOVA ', 90)),
 ('MONGOLIA', ('MONGOLIA ', 100)),
 ('MONTENEGRO', ('MONTENEGRO ', 100)),
 ('MOROCCO', ('MOROCCO ', 100)),
 ('MOZAMBIQUE', ('MOZAMBIQUE ', 100)),
 ('MYANMAR', ('MYANMAR ', 100)),
 ('NAMIBIA', ('NAMIBIA ', 100)),
 ('NEPAL', ('NEPAL ', 100)),
 ('NETHERLANDS (THE)', ('NETHERLANDS ', 95)),
 ('NEW ZEALAND', ('NEW ZEALAND ', 100)),
 ('NICARAGUA', ('NICARAGUA ', 100)),
 ('NIGER (THE)', ('NIGER ', 90)),
 ('NIGERIA', ('NIGERIA ', 100)),
 ('NORTH MACEDONIA', ('NORTH MACEDONIA ', 100)),
 ('NORWAY', ('NORWAY ', 100)),
 ('OMAN', ('OMAN ', 100)),
 ('PAKISTAN', ('PAKISTAN ', 100)),
 ('PANAMA', ('PANAMA ', 100)),
 ('PAPUA NEW GUINEA', ('PAPUA NEW GUINEA ', 100)),
 ('PARAGUAY', ('PARAGUAY ', 100)),
 ('PERU', ('PERU ', 100)),
 ('PHILIPPINES (THE)', ('PHILIPPINES ', 95)),
 ('POLAND', ('POLAND ', 100)),
 ('PORTUGAL', ('PORTUGAL ', 100)),
 ('QATAR', ('QATAR ', 100)),
 ('ROMANIA', ('ROMANIA ', 100)),
 ('RUSSIAN FEDERATION (THE)', ('RUSSIA ', 90)),
 ('RWANDA', ('RWANDA ', 100)),
 ('SAMOA', ('SAMOA ', 100)),
 ('SAO TOME AND PRINCIPE', ('SAO TOME AND PRINCIPE ', 100)),
 ('SAUDI ARABIA', ('SAUDI ARABIA ', 100)),
 ('SENEGAL', ('SENEGAL ', 100)),
 ('SERBIA', ('SERBIA ', 100)),
 ('SEYCHELLES', ('SEYCHELLES ', 100)),
 ('SIERRA LEONE', ('SIERRA LEONE ', 100)),
 ('SINGAPORE', ('SINGAPORE ', 100)),
 ('SLOVAKIA', ('SLOVAKIA ', 100)),
 ('SLOVENIA', ('SLOVENIA ', 100)),
 ('SOLOMON ISLANDS', ('SOLOMON ISLANDS ', 100)),
 ('SOUTH SUDAN', ('SOUTH SUDAN ', 100)),
 ('SPAIN', ('SPAIN ', 100)),
 ('SRI LANKA', ('SRI LANKA ', 100)),
 ('SUDAN (THE)', ('SUDAN ', 90)),
 ('SURINAME', ('SURINAME ', 100)),
 ('SWEDEN', ('SWEDEN ', 100)),
 ('SWITZERLAND', ('SWITZERLAND ', 100)),
 ('TAJIKISTAN', ('TAJIKISTAN ', 100)),
 ('TANZANIA, THE UNITED REPUBLIC OF', ('TANZANIA ', 90)),
 ('THAILAND', ('THAILAND ', 100)),
 ('TIMOR-LESTE', ('TIMOR-LESTE ', 100)),
 ('TOGO', ('TOGO ', 100)),
 ('TRINIDAD AND TOBAGO', ('TRINIDAD AND TOBAGO ', 100)),
 ('TUNISIA', ('TUNISIA ', 100)),
 ('TURKEY', ('TURKMENISTAN ', 75)),
 ('TURKMENISTAN', ('TURKMENISTAN ', 100)),
 ('UGANDA', ('UGANDA ', 100)),
 ('UKRAINE', ('UKRAINE ', 100)),
 ('UNITED ARAB EMIRATES (THE)', ('UNITED ARAB EMIRATES ', 95)),
 ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
  ('UNITED KINGDOM ', 90)),
 ('UNITED STATES MINOR OUTLYING ISLANDS (THE)', ('UNITED STATES ', 90)),
 ('URUGUAY', ('URUGUAY ', 100)),
 ('UZBEKISTAN', ('UZBEKISTAN ', 100)),
 ('VIET NAM', ('VIET NAM ', 100)),
 ('YEMEN', ('YEMEN ', 100)),
 ('ZAMBIA', ('ZAMBIA ', 100)),
 ('ZIMBABWE', ('ZIMBABWE ', 100))]

In [125]:
[(f,fz.extractOne(f, OnlyMerge1)) for f in sorted(OnlyIsos)
 if fz.extractOne(f, OnlyMerge1)[1]>=87]

[('AFGHANISTAN', ('AFGHANISTAN ', 100)),
 ('ALBANIA', ('ALBANIA ', 100)),
 ('ALGERIA', ('ALGERIA ', 100)),
 ('ANGOLA', ('ANGOLA ', 100)),
 ('ANTIGUA AND BARBUDA', ('ANTIGUA AND BARBUDA ', 100)),
 ('ARGENTINA', ('ARGENTINA ', 100)),
 ('ARMENIA', ('ARMENIA ', 100)),
 ('AUSTRALIA', ('AUSTRALIA ', 100)),
 ('AUSTRIA', ('AUSTRIA ', 100)),
 ('AZERBAIJAN', ('AZERBAIJAN ', 100)),
 ('BAHAMAS (THE)', ('BAHAMAS ', 90)),
 ('BAHRAIN', ('BAHRAIN ', 100)),
 ('BANGLADESH', ('BANGLADESH ', 100)),
 ('BARBADOS', ('BARBADOS ', 100)),
 ('BELARUS', ('BELARUS ', 100)),
 ('BELGIUM', ('BELGIUM ', 100)),
 ('BELIZE', ('BELIZE ', 100)),
 ('BENIN', ('BENIN ', 100)),
 ('BHUTAN', ('BHUTAN ', 100)),
 ('BOLIVIA (PLURINATIONAL STATE OF)', ('BOLIVIA ', 90)),
 ('BOSNIA AND HERZEGOVINA', ('BOSNIA AND HERZEGOVINA ', 100)),
 ('BOTSWANA', ('BOTSWANA ', 100)),
 ('BRAZIL', ('BRAZIL ', 100)),
 ('BRUNEI DARUSSALAM', ('BRUNEI ', 90)),
 ('BULGARIA', ('BULGARIA ', 100)),
 ('BURKINA FASO', ('BURKINA FASO ', 100)),
 ('BURUNDI', ('BURUNDI ', 100)),
 ('CABO VERDE', ('CABO VERDE ', 100)),
 ('CAMBODIA', ('CAMBODIA ', 100)),
 ('CAMEROON', ('CAMEROON ', 100)),
 ('CANADA', ('CANADA ', 100)),
 ('CENTRAL AFRICAN REPUBLIC (THE)', ('CENTRAL AFRICAN REPUBLIC ', 95)),
 ('CHAD', ('CHAD ', 100)),
 ('CHILE', ('CHILE ', 100)),
 ('CHINA', ('CHINA ', 100)),
 ('COLOMBIA', ('COLOMBIA ', 100)),
 ('COMOROS (THE)', ('COMOROS ', 90)),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
  ('DEMOCRATIC REPUBLIC OF THE CONGO ', 95)),
 ('COSTA RICA', ('COSTA RICA ', 100)),
 ('CROATIA', ('CROATIA ', 100)),
 ('CYPRUS', ('CYPRUS ', 100)),
 ('CZECHIA', ('CZECHIA ', 100)),
 ("CâˆšÃ®TE D'IVOIRE", ("CÃ”TE D'IVOIRE ", 96)),
 ('DENMARK', ('DENMARK ', 100)),
 ('DJIBOUTI', ('DJIBOUTI ', 100)),
 ('DOMINICAN REPUBLIC (THE)', ('DOMINICAN REPUBLIC ', 95)),
 ('ECUADOR', ('ECUADOR ', 100)),
 ('EGYPT', ('EGYPT ', 100)),
 ('EL SALVADOR', ('EL SALVADOR ', 100)),
 ('EQUATORIAL GUINEA', ('EQUATORIAL GUINEA ', 100)),
 ('ESTONIA', ('ESTONIA ', 100)),
 ('ESWATINI', ('ESWATINI ', 100)),
 ('ETHIOPIA', ('ETHIOPIA ', 100)),
 ('FIJI', ('FIJI ', 100)),
 ('FINLAND', ('FINLAND ', 100)),
 ('FRANCE', ('FRANCE ', 100)),
 ('GABON', ('GABON ', 100)),
 ('GAMBIA (THE)', ('THE GAMBIA ', 95)),
 ('GEORGIA', ('GEORGIA ', 100)),
 ('GERMANY', ('GERMANY ', 100)),
 ('GHANA', ('GHANA ', 100)),
 ('GREECE', ('GREECE ', 100)),
 ('GRENADA', ('GRENADA ', 100)),
 ('GUATEMALA', ('GUATEMALA ', 100)),
 ('GUINEA', ('GUINEA ', 100)),
 ('GUINEA-BISSAU', ('GUINEA-BISSAU ', 100)),
 ('GUYANA', ('GUYANA ', 100)),
 ('HAITI', ('HAITI ', 100)),
 ('HONDURAS', ('HONDURAS ', 100)),
 ('HUNGARY', ('HUNGARY ', 100)),
 ('ICELAND', ('ICELAND ', 100)),
 ('INDIA', ('INDIA ', 100)),
 ('INDONESIA', ('INDONESIA ', 100)),
 ('IRAN (ISLAMIC REPUBLIC OF)', ('IRAN ', 90)),
 ('IRAQ', ('IRAQ ', 100)),
 ('IRELAND', ('IRELAND ', 100)),
 ('ITALY', ('ITALY ', 100)),
 ('JAMAICA', ('JAMAICA ', 100)),
 ('JAPAN', ('JAPAN ', 100)),
 ('JORDAN', ('JORDAN ', 100)),
 ('KAZAKHSTAN', ('KAZAKHSTAN ', 100)),
 ('KENYA', ('KENYA ', 100)),
 ('KUWAIT', ('KUWAIT ', 100)),
 ('KYRGYZSTAN', ('KYRGYZSTAN ', 100)),
 ('LATVIA', ('LATVIA ', 100)),
 ('LEBANON', ('LEBANON ', 100)),
 ('LESOTHO', ('LESOTHO ', 100)),
 ('LIBERIA', ('LIBERIA ', 100)),
 ('LIBYA', ('LIBYA ', 100)),
 ('LITHUANIA', ('LITHUANIA ', 100)),
 ('LUXEMBOURG', ('LUXEMBOURG ', 100)),
 ('MADAGASCAR', ('MADAGASCAR ', 100)),
 ('MALAWI', ('MALAWI ', 100)),
 ('MALAYSIA', ('MALAYSIA ', 100)),
 ('MALDIVES', ('MALDIVES ', 100)),
 ('MALI', ('MALI ', 100)),
 ('MALTA', ('MALTA ', 100)),
 ('MAURITANIA', ('MAURITANIA ', 100)),
 ('MAURITIUS', ('MAURITIUS ', 100)),
 ('MEXICO', ('MEXICO ', 100)),
 ('MICRONESIA (FEDERATED STATES OF)', ('FEDERATED STATES OF MICRONESIA ', 95)),
 ('MOLDOVA (THE REPUBLIC OF)', ('MOLDOVA ', 90)),
 ('MONGOLIA', ('MONGOLIA ', 100)),
 ('MONTENEGRO', ('MONTENEGRO ', 100)),
 ('MOROCCO', ('MOROCCO ', 100)),
 ('MOZAMBIQUE', ('MOZAMBIQUE ', 100)),
 ('MYANMAR', ('MYANMAR ', 100)),
 ('NAMIBIA', ('NAMIBIA ', 100)),
 ('NEPAL', ('NEPAL ', 100)),
 ('NETHERLANDS (THE)', ('NETHERLANDS ', 95)),
 ('NEW ZEALAND', ('NEW ZEALAND ', 100)),
 ('NICARAGUA', ('NICARAGUA ', 100)),
 ('NIGER (THE)', ('NIGER ', 90)),
 ('NIGERIA', ('NIGERIA ', 100)),
 ('NORTH MACEDONIA', ('NORTH MACEDONIA ', 100)),
 ('NORWAY', ('NORWAY ', 100)),
 ('OMAN', ('OMAN ', 100)),
 ('PAKISTAN', ('PAKISTAN ', 100)),
 ('PANAMA', ('PANAMA ', 100)),
 ('PAPUA NEW GUINEA', ('PAPUA NEW GUINEA ', 100)),
 ('PARAGUAY', ('PARAGUAY ', 100)),
 ('PERU', ('PERU ', 100)),
 ('PHILIPPINES (THE)', ('PHILIPPINES ', 95)),
 ('POLAND', ('POLAND ', 100)),
 ('PORTUGAL', ('PORTUGAL ', 100)),
 ('QATAR', ('QATAR ', 100)),
 ('ROMANIA', ('ROMANIA ', 100)),
 ('RUSSIAN FEDERATION (THE)', ('RUSSIA ', 90)),
 ('RWANDA', ('RWANDA ', 100)),
 ('SAMOA', ('SAMOA ', 100)),
 ('SAO TOME AND PRINCIPE', ('SAO TOME AND PRINCIPE ', 100)),
 ('SAUDI ARABIA', ('SAUDI ARABIA ', 100)),
 ('SENEGAL', ('SENEGAL ', 100)),
 ('SERBIA', ('SERBIA ', 100)),
 ('SEYCHELLES', ('SEYCHELLES ', 100)),
 ('SIERRA LEONE', ('SIERRA LEONE ', 100)),
 ('SINGAPORE', ('SINGAPORE ', 100)),
 ('SLOVAKIA', ('SLOVAKIA ', 100)),
 ('SLOVENIA', ('SLOVENIA ', 100)),
 ('SOLOMON ISLANDS', ('SOLOMON ISLANDS ', 100)),
 ('SOUTH SUDAN', ('SOUTH SUDAN ', 100)),
 ('SPAIN', ('SPAIN ', 100)),
 ('SRI LANKA', ('SRI LANKA ', 100)),
 ('SUDAN (THE)', ('SUDAN ', 90)),
 ('SURINAME', ('SURINAME ', 100)),
 ('SWEDEN', ('SWEDEN ', 100)),
 ('SWITZERLAND', ('SWITZERLAND ', 100)),
 ('TAJIKISTAN', ('TAJIKISTAN ', 100)),
 ('TANZANIA, THE UNITED REPUBLIC OF', ('TANZANIA ', 90)),
 ('THAILAND', ('THAILAND ', 100)),
 ('TIMOR-LESTE', ('TIMOR-LESTE ', 100)),
 ('TOGO', ('TOGO ', 100)),
 ('TRINIDAD AND TOBAGO', ('TRINIDAD AND TOBAGO ', 100)),
 ('TUNISIA', ('TUNISIA ', 100)),
 ('TURKMENISTAN', ('TURKMENISTAN ', 100)),
 ('UGANDA', ('UGANDA ', 100)),
 ('UKRAINE', ('UKRAINE ', 100)),
 ('UNITED ARAB EMIRATES (THE)', ('UNITED ARAB EMIRATES ', 95)),
 ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
  ('UNITED KINGDOM ', 90)),
 ('UNITED STATES MINOR OUTLYING ISLANDS (THE)', ('UNITED STATES ', 90)),
 ('URUGUAY', ('URUGUAY ', 100)),
 ('UZBEKISTAN', ('UZBEKISTAN ', 100)),
 ('VIET NAM', ('VIET NAM ', 100)),
 ('YEMEN', ('YEMEN ', 100)),
 ('ZAMBIA', ('ZAMBIA ', 100)),
 ('ZIMBABWE', ('ZIMBABWE ', 100))]

In [126]:
changesFragile1={f:fz.extractOne(f, OnlyMerge1)[0] 
                 for f in sorted(OnlyIsos)
                 if fz.extractOne(f, OnlyMerge1)[1] >=87}
#dict of matches
changesFragile1

{'AFGHANISTAN': 'AFGHANISTAN ',
 'ALBANIA': 'ALBANIA ',
 'ALGERIA': 'ALGERIA ',
 'ANGOLA': 'ANGOLA ',
 'ANTIGUA AND BARBUDA': 'ANTIGUA AND BARBUDA ',
 'ARGENTINA': 'ARGENTINA ',
 'ARMENIA': 'ARMENIA ',
 'AUSTRALIA': 'AUSTRALIA ',
 'AUSTRIA': 'AUSTRIA ',
 'AZERBAIJAN': 'AZERBAIJAN ',
 'BAHAMAS (THE)': 'BAHAMAS ',
 'BAHRAIN': 'BAHRAIN ',
 'BANGLADESH': 'BANGLADESH ',
 'BARBADOS': 'BARBADOS ',
 'BELARUS': 'BELARUS ',
 'BELGIUM': 'BELGIUM ',
 'BELIZE': 'BELIZE ',
 'BENIN': 'BENIN ',
 'BHUTAN': 'BHUTAN ',
 'BOLIVIA (PLURINATIONAL STATE OF)': 'BOLIVIA ',
 'BOSNIA AND HERZEGOVINA': 'BOSNIA AND HERZEGOVINA ',
 'BOTSWANA': 'BOTSWANA ',
 'BRAZIL': 'BRAZIL ',
 'BRUNEI DARUSSALAM': 'BRUNEI ',
 'BULGARIA': 'BULGARIA ',
 'BURKINA FASO': 'BURKINA FASO ',
 'BURUNDI': 'BURUNDI ',
 'CABO VERDE': 'CABO VERDE ',
 'CAMBODIA': 'CAMBODIA ',
 'CAMEROON': 'CAMEROON ',
 'CANADA': 'CANADA ',
 'CENTRAL AFRICAN REPUBLIC (THE)': 'CENTRAL AFRICAN REPUBLIC ',
 'CHAD': 'CHAD ',
 'CHILE': 'CHILE ',
 'CHINA': 'CHINA ',
 'COLOMBIA': 'COLOMBIA ',
 'COMOROS (THE)': 'COMOROS ',
 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)': 'DEMOCRATIC REPUBLIC OF THE CONGO ',
 'COSTA RICA': 'COSTA RICA ',
 'CROATIA': 'CROATIA ',
 'CYPRUS': 'CYPRUS ',
 'CZECHIA': 'CZECHIA ',
 "CâˆšÃ®TE D'IVOIRE": "CÃ”TE D'IVOIRE ",
 'DENMARK': 'DENMARK ',
 'DJIBOUTI': 'DJIBOUTI ',
 'DOMINICAN REPUBLIC (THE)': 'DOMINICAN REPUBLIC ',
 'ECUADOR': 'ECUADOR ',
 'EGYPT': 'EGYPT ',
 'EL SALVADOR': 'EL SALVADOR ',
 'EQUATORIAL GUINEA': 'EQUATORIAL GUINEA ',
 'ESTONIA': 'ESTONIA ',
 'ESWATINI': 'ESWATINI ',
 'ETHIOPIA': 'ETHIOPIA ',
 'FIJI': 'FIJI ',
 'FINLAND': 'FINLAND ',
 'FRANCE': 'FRANCE ',
 'GABON': 'GABON ',
 'GAMBIA (THE)': 'THE GAMBIA ',
 'GEORGIA': 'GEORGIA ',
 'GERMANY': 'GERMANY ',
 'GHANA': 'GHANA ',
 'GREECE': 'GREECE ',
 'GRENADA': 'GRENADA ',
 'GUATEMALA': 'GUATEMALA ',
 'GUINEA': 'GUINEA ',
 'GUINEA-BISSAU': 'GUINEA-BISSAU ',
 'GUYANA': 'GUYANA ',
 'HAITI': 'HAITI ',
 'HONDURAS': 'HONDURAS ',
 'HUNGARY': 'HUNGARY ',
 'ICELAND': 'ICELAND ',
 'INDIA': 'INDIA ',
 'INDONESIA': 'INDONESIA ',
 'IRAN (ISLAMIC REPUBLIC OF)': 'IRAN ',
 'IRAQ': 'IRAQ ',
 'IRELAND': 'IRELAND ',
 'ITALY': 'ITALY ',
 'JAMAICA': 'JAMAICA ',
 'JAPAN': 'JAPAN ',
 'JORDAN': 'JORDAN ',
 'KAZAKHSTAN': 'KAZAKHSTAN ',
 'KENYA': 'KENYA ',
 'KUWAIT': 'KUWAIT ',
 'KYRGYZSTAN': 'KYRGYZSTAN ',
 'LATVIA': 'LATVIA ',
 'LEBANON': 'LEBANON ',
 'LESOTHO': 'LESOTHO ',
 'LIBERIA': 'LIBERIA ',
 'LIBYA': 'LIBYA ',
 'LITHUANIA': 'LITHUANIA ',
 'LUXEMBOURG': 'LUXEMBOURG ',
 'MADAGASCAR': 'MADAGASCAR ',
 'MALAWI': 'MALAWI ',
 'MALAYSIA': 'MALAYSIA ',
 'MALDIVES': 'MALDIVES ',
 'MALI': 'MALI ',
 'MALTA': 'MALTA ',
 'MAURITANIA': 'MAURITANIA ',
 'MAURITIUS': 'MAURITIUS ',
 'MEXICO': 'MEXICO ',
 'MICRONESIA (FEDERATED STATES OF)': 'FEDERATED STATES OF MICRONESIA ',
 'MOLDOVA (THE REPUBLIC OF)': 'MOLDOVA ',
 'MONGOLIA': 'MONGOLIA ',
 'MONTENEGRO': 'MONTENEGRO ',
 'MOROCCO': 'MOROCCO ',
 'MOZAMBIQUE': 'MOZAMBIQUE ',
 'MYANMAR': 'MYANMAR ',
 'NAMIBIA': 'NAMIBIA ',
 'NEPAL': 'NEPAL ',
 'NETHERLANDS (THE)': 'NETHERLANDS ',
 'NEW ZEALAND': 'NEW ZEALAND ',
 'NICARAGUA': 'NICARAGUA ',
 'NIGER (THE)': 'NIGER ',
 'NIGERIA': 'NIGERIA ',
 'NORTH MACEDONIA': 'NORTH MACEDONIA ',
 'NORWAY': 'NORWAY ',
 'OMAN': 'OMAN ',
 'PAKISTAN': 'PAKISTAN ',
 'PANAMA': 'PANAMA ',
 'PAPUA NEW GUINEA': 'PAPUA NEW GUINEA ',
 'PARAGUAY': 'PARAGUAY ',
 'PERU': 'PERU ',
 'PHILIPPINES (THE)': 'PHILIPPINES ',
 'POLAND': 'POLAND ',
 'PORTUGAL': 'PORTUGAL ',
 'QATAR': 'QATAR ',
 'ROMANIA': 'ROMANIA ',
 'RUSSIAN FEDERATION (THE)': 'RUSSIA ',
 'RWANDA': 'RWANDA ',
 'SAMOA': 'SAMOA ',
 'SAO TOME AND PRINCIPE': 'SAO TOME AND PRINCIPE ',
 'SAUDI ARABIA': 'SAUDI ARABIA ',
 'SENEGAL': 'SENEGAL ',
 'SERBIA': 'SERBIA ',
 'SEYCHELLES': 'SEYCHELLES ',
 'SIERRA LEONE': 'SIERRA LEONE ',
 'SINGAPORE': 'SINGAPORE ',
 'SLOVAKIA': 'SLOVAKIA ',
 'SLOVENIA': 'SLOVENIA ',
 'SOLOMON ISLANDS': 'SOLOMON ISLANDS ',
 'SOUTH SUDAN': 'SOUTH SUDAN ',
 'SPAIN': 'SPAIN ',
 'SRI LANKA': 'SRI LANKA ',
 'SUDAN (THE)': 'SUDAN ',
 'SURINAME': 'SURINAME ',
 'SWEDEN': 'SWEDEN ',
 'SWITZERLAND': 'SWITZERLAND ',
 'TAJIKISTAN': 'TAJIKISTAN ',
 'TANZANIA, THE UNITED REPUBLIC OF': 'TANZANIA ',
 'THAILAND': 'THAILAND ',
 'TIMOR-LESTE': 'TIMOR-LESTE ',
 'TOGO': 'TOGO ',
 'TRINIDAD AND TOBAGO': 'TRINIDAD AND TOBAGO ',
 'TUNISIA': 'TUNISIA ',
 'TURKMENISTAN': 'TURKMENISTAN ',
 'UGANDA': 'UGANDA ',
 'UKRAINE': 'UKRAINE ',
 'UNITED ARAB EMIRATES (THE)': 'UNITED ARAB EMIRATES ',
 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)': 'UNITED KINGDOM ',
 'UNITED STATES MINOR OUTLYING ISLANDS (THE)': 'UNITED STATES ',
 'URUGUAY': 'URUGUAY ',
 'UZBEKISTAN': 'UZBEKISTAN ',
 'VIET NAM': 'VIET NAM ',
 'YEMEN': 'YEMEN ',
 'ZAMBIA': 'ZAMBIA ',
 'ZIMBABWE': 'ZIMBABWE '}

In [127]:
# make the changes
isos.Country.replace(to_replace=changesFragile1,inplace=True)

In [128]:
# second try
OnlyMerge1=set(merge1.Country)-set(isos.Country)
OnlyIsos=set(isos.Country)-set(merge1.Country)
[(f,fz.extractOne(f, OnlyMerge1)) for f in sorted(OnlyIsos)]

[('CONGO (THE)', ('REPUBLIC OF THE CONGO ', 86)),
 ('CUBA', ('SAINT LUCIA ', 45)),
 ('KOREA (THE REPUBLIC OF)', ('SOUTH KOREA ', 86)),
 ("LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)", ('REPUBLIC OF THE CONGO ', 86)),
 ('TURKEY', ('TÃœRKIYE ', 67))]

In [129]:
# second dict of changes
changesFragile2={f:fz.extractOne(f, OnlyMerge1)[0] 
                 for f in sorted(OnlyIsos)
                 if 74<=fz.extractOne(f, OnlyMerge1)[1]}

#dict of matches
changesFragile2

{'CONGO (THE)': 'REPUBLIC OF THE CONGO ',
 'KOREA (THE REPUBLIC OF)': 'SOUTH KOREA ',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)": 'REPUBLIC OF THE CONGO '}

In [130]:
# make the changes
isos.Country.replace(to_replace=changesFragile2,inplace=True)

In [131]:
OnlyMerge1=set(merge1.Country)-set(isos.Country)
OnlyIsos=set(isos.Country)-set(merge1.Country)
[(f,fz.extractOne(f, OnlyMerge1)) for f in sorted(OnlyIsos)]

[('CUBA', ('SAINT LUCIA ', 45)), ('TURKEY', ('TÃœRKIYE ', 67))]

In [132]:
# third try
changesFragile3={f:fz.extractOne(f, OnlyMerge1)[0] 
                 for f in sorted(OnlyIsos)
                 if 54==fz.extractOne(f, OnlyMerge1)[1]}

#dict of matches
changesFragile3

{}

In [133]:
#merge on Country
merge1Isos=merge1.merge(isos) 
merge1Isos

,Country,Debt ($M),Gov. Health Exp.($M),HDI,Officialstatename,InternetccTLD,iso2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [134]:
merge1.merge(isos, left_on='Country',right_on='Country').shape

(169, 8)

In [135]:
# DATA CLEANING
merge1Isos.columns

Index(['Country', 'Debt ($M)', 'Gov. Health Exp.($M)', 'HDI',
       'Officialstatename', 'InternetccTLD', 'iso2', 'iso3'],
      dtype='object')

In [136]:
merge1Isos.columns.to_list()

['Country',
 'Debt ($M)',
 'Gov. Health Exp.($M)',
 'HDI',
 'Officialstatename',
 'InternetccTLD',
 'iso2',
 'iso3']

In [137]:
merge1Isos=merge1Isos.rename(columns={"Debt ($M)": "Debt_mdd"})
merge1Isos

,Country,Debt_mdd,Gov. Health Exp.($M),HDI,Officialstatename,InternetccTLD,iso2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [138]:
merge1Isos=merge1Isos.rename(columns={"Gov. Health Exp.($M)": "Health_mdd"})
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Officialstatename,InternetccTLD,iso2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [139]:
merge1Isos=merge1Isos.rename(columns={"Officialstatename": "Official_state_name"})
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,InternetccTLD,iso2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [140]:
merge1Isos=merge1Isos.rename(columns={"InternetccTLD": "Internet TLD"})
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,Internet TLD,iso2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [141]:
merge1Isos=merge1Isos.rename(columns={"iso2": "iso_2"})
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,Internet TLD,iso_2,iso3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [142]:
merge1Isos=merge1Isos.rename(columns={"iso3": "iso_3"})
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,Internet TLD,iso_2,iso_3
0,UNITED STATES,"29,476,402","3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,"3,151,536","87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,"2,711,576","445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,"3,106,402","279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,"12,783,842","213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,"145,342","7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,"18,092",183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,"24,538",446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,"1,905,213",732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [143]:
merge1Isos.columns

Index(['Country', 'Debt_mdd', 'Health_mdd', 'HDI', 'Official_state_name',
       'Internet TLD', 'iso_2', 'iso_3'],
      dtype='object')

In [144]:
merge1Isos['Debt_mdd']=merge1Isos['Debt_mdd'].str.replace(',', ' ')
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,Internet TLD,iso_2,iso_3
0,UNITED STATES,29 476 402,"3,590,550,278,000.00",0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,3 151 536,"87,073,157,032.30",0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,2 711 576,"445,746,483,000.00",0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,3 106 402,"279,900,617,256.00",0.903,The French Republic,.fr,FR,FRA
4,JAPAN,12 783 842,"213,703,956,338.90",0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,145 342,"7,452.90",0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,18 092,183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,24 538,446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,1 905 213,732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE

In [145]:
merge1Isos['Health_mdd']=merge1Isos['Health_mdd'].str.replace(',', ' ')
merge1Isos

,Country,Debt_mdd,Health_mdd,HDI,Official_state_name,Internet TLD,iso_2,iso_3
0,UNITED STATES,29 476 402,3 590 550 278 000.00,0.921,"BakerÂ¬â€ Island, HowlandÂ¬â€ Island, JarvisÂ¬â€ Island...",NaN,UM,UMI
1,UNITED KINGDOM,3 151 536,87 073 157 032.30,0.929,The United Kingdom of Great Britain and Northe...,.uk,GB,GBR
2,GERMANY,2 711 576,445 746 483 000.00,0.942,The Federal Republic of Germany,.de,DE,DEU
3,FRANCE,3 106 402,279 900 617 256.00,0.903,The French Republic,.fr,FR,FRA
4,JAPAN,12 783 842,213 703 956 338.90,0.925,Japan,.jp,JP,JPN
...,...,...,...,...,...,...,...,...
164,VIET NAM,145 342,7 452.90,0.703,The Socialist Republic of Viet Nam,.vn,VN,VNM
165,SAMOA,364,36.2,0.707,The Independent State of Samoa,.ws,WS,WSM
166,YEMEN,18 092,183,0.455,The Republic of Yemen,.ye,YE,YEM
167,ZAMBIA,24 538,446.9,0.565,The Republic of Zambia,.zm,ZM,ZMB
168,ZIMBABWE,1 905 213,732.5,0.593,The Republic of Zimbabwe,.zw,ZW,ZWE